### PR TITLE
Upkeep

### PR DESCRIPTION
**Pull request by dunkenwg**
Error with `nrp_read_ctd_file()` causing six tests and knitting of README to fail. `~/nrp/inst/extdata/ctd/2018/KL1_27Aug2018008downcast.cnv` doesn't have a column called `Conductivity2`.

```
Error (test-ctd.R:198:3): getOption nrp.dp_path works
<purrr_error_indexed/rlang_error/error/condition>
Error in `map(paths, ~nrp_read_ctd_file(., db_path = db_path))`: ℹ In index: 1.
ℹ With name:
~nrp/inst/extdata/ctd/2018/KL1_27Aug2018008downcast.cnv.
Caused by error in `select()`:
! Can't select columns that don't exist.
✖ Column `Conductivity2` doesn't exist.
```

### CODE REVIEW

**Comment by evanamiesgalonski** [comment]
thanks for uncovering this one Duncan, I'll have to wait till i have some time next month to review/troubleshoot

**Comment by dunkenwg** [comment]
@evanamiesgalonski, when you get a chance would you be able to review this?

**Comment by evanamiesgalonski** [comment]
Thanks for the reminder @dunkenwg.

`nrp_read_ctd_file` is a wrapper on `oce::read.ctd.sbe` which now apparently only reads in one measure of conductivity as of `oce` version 1.8-3. I'll likely file an issue with them if i get permission from the client to share the data needed for a reprex. There may also be a unit conversion work around. Either way we can't fix right away. 

This is one of those times that actions turning themselves off due to inactivity causes us to miss problems with dependancies when we come back to do maintenance.

So for the package upkeep we can either:
1 - merge these changes now given the function is broken regardless of these changes (as cmd check fail is due to the dependancy on the oce package)
2 - put this pr on hold and hope to merge after the fix (may need to navigate merge conflicts)

@aylapear which do you think would fit our best practices?

**Comment by aylapear** [comment]
We don't have a policy on this but I think that in this situation. I would merge in the housekeeping stuff since we have confirmed it has not caused the breaking change and post an issue about the error so people are aware there is a bug if they try to use the package/function.

**Review by evanamiesgalonski — APPROVED** [review]
Thanks Duncan, I'll fix the error once upkeep changes merged

**Pull request merged**
